//
//  Workspace.swift
//  Config
//
//  Created by summercat on 12/14/24.
//

import ProjectDescription

let workspace = Workspace(
  name: "Piece-iOS",
  projects: [
    "App/**",
    "Data/**",
    "Domain/**",
    "Presentation/**",
    "Utility/**",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled
  )
)
